routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index');
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/meta', 'Web\Admin\MetaController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('/admin/tahun', 'Web\Admin\TahunController');
Route::resource('/admin/tahap', 'Web\Admin\TahapController');
Route::resource('/admin/rubah', 'Web\Admin\CookieController');

Route::resource('/admin/dana', 'Web\Admin\DanaController');
Route::resource('/admin/saldo', 'Web\Admin\SaldoController');

Route::resource('/admin/komponen', 'Web\Admin\KomponenController');
Route::get('/admin/subkomponen/index/{id}', 'Web\Admin\SubKomponenController@index');
Route::resource('/admin/subkomponen', 'Web\Admin\SubKomponenController');

Route::get('/admin/nota/index/{id}', 'Web\Admin\NotaController@index');
Route::resource('/admin/nota', 'Web\Admin\NotaController');

Route::resource('/admin/barang', 'Web\Admin\BarangController');
Route::post('importbarang', 'Web\Admin\BarangController@import')->name('importbarang');
Route::get('exportbarang', 'Web\Admin\BarangController@export')->name('exportbarang');

Route::resource('/admin/toko', 'Web\Admin\TokoController');
Route::post('importtoko', 'Web\Admin\TokoController@import')->name('importtoko');
Route::get('exporttoko', 'Web\Admin\TokoController@export')->name('exporttoko');

Route::resource('/admin/notabarang', 'Web\Admin\NotaBarangController');

Route::resource('/admin/cetak/notas', 'Web\Admin\CetakNotaController');
Route::resource('/admin/cetak/apd', 'Web\Admin\CetakAPDController');
Route::resource('/admin/cetak/bku', 'Web\Admin\CetakBKUController');
Route::resource('/admin/cetak/bpp', 'Web\Admin\CetakBPPController');
Route::resource('/admin/cetak/rlpd', 'Web\Admin\CetakRLPDController');
Route::resource('/admin/cetak/bkp', 'Web\Admin\CetakBKPController');

app/Toko.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Toko extends Model
{
    protected $guarded = [];
    
    protected $fillable = [
        'toko','jenis'
    ];

    public function nota()
    {
        return $this->hasMany('App\Nota');
    }
    public function barang()
    {
        return $this->hasMany('App\Barang');
    }
}

app/Http/Controllers/Web/Admin/TokoController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Exports\TokoExport;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\TokoRequest;
use App\Nota;
use App\Toko;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Imports\TokoImport;
use Excel;

class TokoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no = 1;
        $toko = Toko::orderBy('jenis', 'ASC')->orderBy('toko', 'ASC')->get()->all();
        return view('admin.toko.beranda', compact('toko', 'no'));
    }

    public function import(Request $request)
    {
        if ($request->hasFile('file')) {
            $file = $request->file('file'); //GET FILE
            Excel::import(new TokoImport, $file); //IMPORT FILE 
            return redirect()->back();
        }
    }

    public function export() 
    {
        return Excel::download(new TokoExport, 'data_toko.xlsx');
    }

    public function create()
    {
        //
    }

    public function store(TokoRequest $request)
    {
        $data = $request->all();

        Toko::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Toko " . $request->toko;
        History::create($histori);

        $notification = array(
            'message' => 'Data Toko "' . $request->toko . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('toko.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit(Toko $toko)
    {
        return view('admin.toko.edit', compact('toko'));
    }

    public function update(TokoRequest $request, Toko $toko)
    {
        $toko->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Toko " . $request->toko;
        History::create($histori);

        $notification = array(
            'message' => 'Data Toko "' . $request->toko . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('toko.index')->with($notification);
    }

    public function destroy(Toko $toko)
    {
        $nota = Nota::where('toko_id', $toko->id)->get()->first();

        if (empty($nota)) {
            // HISTORI
            $histori['user'] = Auth::user()->name;
            $histori['info'] = "Hapus";
            $histori['desc_info'] = "Data Toko " . $toko->toko;
            History::create($histori);

            $notification = array(
                'message' => 'Data Toko "' . $toko->toko . '" berhasil dihapus.',
                'alert-type' => 'error'
            );

            $toko->delete();

            return redirect()->route('toko.index')->with($notification);
        } else {

            $notification = array(
                'message' => 'Data Toko "' . $toko->toko . '" terinput di Nota.',
                'alert-type' => 'warning'
            );

            return redirect()->route('toko.index')->with($notification);
        }
    }
}

resources/views/admin/toko/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Toko
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-12">
      <a href="{{ route('exporttoko') }}" class="btn btn-primary">Download Data Toko</a><br><br>
    </div>
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Toko</h3>
        </div>
        <div class="box-body" style="overflow-x:auto;">
          <div class="col-md-6">
            <form action="{{ route('toko.store') }}" class="form-horizontal" method="POST">
              @csrf
              <div class="form-group">
                <label for="toko" class="col-sm-4 control-label">Nama Toko</label>

                <div class="col-sm-8">
                  <input type="text" name="toko" class="form-control" placeholder="Nama Toko">
                  <small class="text-danger">{{ $errors->first('toko') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="jenis" class="col-sm-4 control-label">Jenis Toko</label>

                <div class="col-sm-8">
                  <input type="text" name="jenis" class="form-control" placeholder="ex : Fotocopy / Komputer / Olahraga">
                  <small class="text-danger">{{ $errors->first('jenis') }}</small>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Simpan</button>

            </form>
          </div>
          <div class="col-md-6">
            <form action="{{ route('importtoko') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
              @csrf
              <div class="form-group">
                <label for="toko" class="col-sm-4 control-label">Import Toko</label>
                <div class="col-sm-8">
                  <input type="file" name="file" class="form-control">
                  Pastikan file ber extensi .xls atau .xlsx
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Unggah</button>
            </form>
          </div>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>No</th>
                <th>Jenis Toko</th>
                <th>Toko</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

              @foreach($toko as $item)
              <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $item->jenis }}</td>
                <td>{{ $item->toko }}</td>
                <td align="center">
                  <form action="{{ route('toko.destroy',$item->id) }}" method="POST">
                    <a class="btn btn-success" href="{{ route('toko.edit',$item->id) }}">Ubah</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/toko/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Toko
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ubah Data Toko</h3>
        </div>

        <div class="box-body">
          <form action="{{ route('toko.update', $toko->id) }}" class="form-horizontal" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">
              <label for="toko" class="col-sm-2 control-label">Nama Toko</label>

              <div class="col-sm-10">
                <input type="text" name="toko" value="{{$toko->toko}}" class="form-control" placeholder="Nama Toko">
                <small class="text-danger">{{ $errors->first('toko') }}</small>
              </div>
            </div>
            <div class="form-group">
              <label for="jenis" class="col-sm-2 control-label">Jenis Toko</label>

              <div class="col-sm-10">
                <input type="text" name="jenis" value="{{$toko->jenis}}" class="form-control" placeholder="ex : Fotocopy / Komputer / Olahraga">
                <small class="text-danger">{{ $errors->first('jenis') }}</small>
              </div>
            </div>

            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
          </form>
        </div>

      </div>
    </div>
  </div>
</div>
</div>
@endsection