routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index');
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/meta', 'Web\Admin\MetaController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('/admin/tahun', 'Web\Admin\TahunController');
Route::resource('/admin/tahap', 'Web\Admin\TahapController');
Route::resource('/admin/rubah', 'Web\Admin\CookieController');

Route::resource('/admin/dana', 'Web\Admin\DanaController');
Route::resource('/admin/saldo', 'Web\Admin\SaldoController');

Route::resource('/admin/komponen', 'Web\Admin\KomponenController');
Route::get('/admin/subkomponen/index/{id}', 'Web\Admin\SubKomponenController@index');
Route::resource('/admin/subkomponen', 'Web\Admin\SubKomponenController');

Route::get('/admin/nota/index/{id}', 'Web\Admin\NotaController@index');
Route::resource('/admin/nota', 'Web\Admin\NotaController');

Route::resource('/admin/barang', 'Web\Admin\BarangController');
Route::post('importbarang', 'Web\Admin\BarangController@import')->name('importbarang');
Route::get('exportbarang', 'Web\Admin\BarangController@export')->name('exportbarang');

Route::resource('/admin/toko', 'Web\Admin\TokoController');
Route::post('importtoko', 'Web\Admin\TokoController@import')->name('importtoko');
Route::get('exporttoko', 'Web\Admin\TokoController@export')->name('exporttoko');

Route::resource('/admin/notabarang', 'Web\Admin\NotaBarangController');

Route::resource('/admin/cetak/notas', 'Web\Admin\CetakNotaController');
Route::resource('/admin/cetak/apd', 'Web\Admin\CetakAPDController');
Route::resource('/admin/cetak/bku', 'Web\Admin\CetakBKUController');
Route::resource('/admin/cetak/bpp', 'Web\Admin\CetakBPPController');
Route::resource('/admin/cetak/rlpd', 'Web\Admin\CetakRLPDController');
Route::resource('/admin/cetak/bkp', 'Web\Admin\CetakBKPController');

app/Dana.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dana extends Model
{
    protected $fillable = [
        'tahap_id','tanggal','tanggal_bku','dana','ket','tipe'
    ];

    protected $dates = ['tanggal','tanggal_bku'];

    public function tahap()
    {
        return $this->belongsTo('App\Tahap', 'tahap_id');
    }
}

app/Http/Controllers/Web/Admin/DanaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Dana;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\DanaRequest;
use App\Tahap;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;

class DanaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no =1;
        $tahap = Cookie::get('tahap');
        $tahun_id = Cookie::get('id_tahun');
        $tahap_id = Tahap::where('tahun_id',$tahun_id)->where('tahap',$tahap)->get()->first();

        $dana = Dana::where('tahap_id', $tahap_id->id)->orderBy('tanggal', 'ASC')->get()->all();

        $total_dana = Dana::where('tahap_id', $tahap_id->id)->where('tipe','Masuk')->sum('dana');
        return view('admin.dana.beranda', compact('dana','no','total_dana'));
    }

    public function create()
    {
        //
    }

    public function store(DanaRequest $request)
    {
        $tahap = Cookie::get('tahap');
        $tahun_id = Cookie::get('id_tahun');
        $tahap_id = Tahap::where('tahun_id',$tahun_id)->where('tahap',$tahap)->get()->first();

        $data = $request->all();
        $data['tahap_id'] = $tahap_id->id;

        Dana::create($data);
        
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Dana " . $request->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Dana "' . $request->ket . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('dana.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit(Dana $dana)
    {
        return view('admin.dana.edit',compact('dana'));
    }

    public function update(DanaRequest $request, Dana $dana)
    {
        $dana->update($request->all());
  
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Dana " . $request->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Dana "' . $request->ket . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('dana.index')->with($notification);
    }

    public function destroy(Dana $dana)
    {
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Dana " . $dana->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Dana "' . $dana->ket . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $dana->delete();

        return redirect()->route('dana.index')->with($notification);
    }
}

resources/views/admin/dana/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Dana
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Dana</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <form action="{{ route('dana.store') }}" class="form-horizontal" method="POST">
            @csrf

            <div class="col-md-6">
              <div class="form-group">
                <label for="tanggal" class="col-sm-2 control-label">Tanggal</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal" class="form-control" placeholder="Tanggal">
                  <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tanggal_bku" class="col-sm-2 control-label">Tanggal BKU</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal_bku" class="form-control" placeholder="Tanggal BKU">
                  <small class="text-danger">{{ $errors->first('tanggal_bku') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tipe" class="col-sm-2 control-label">Tipe</label>
                <div class="col-sm-10">
                  <select class="form-control" name="tipe">
                    <option value="Tarik">Tarik</option>
                    <option value="Masuk">Masuk</option>
                  </select>
                  <small class="text-danger">{{ $errors->first('tipe') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tahun" class="col-sm-2 control-label">Dana</label>

                <div class="col-sm-10">
                  <input type="number" name="dana" class="form-control" placeholder="Dana">
                  <small class="text-danger">{{ $errors->first('dana') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="ket" class="col-sm-2 control-label">Keterangan</label>

                <div class="col-sm-10">
                  <input type="text" name="ket" class="form-control" placeholder="ex : Penarikan Dana 1">
                  <small class="text-danger">{{ $errors->first('ket') }}</small>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Simpan</button>
            </div>

          </form>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <h3><b>Total Dana : {{ number_format($total_dana, 0, ".", ".") }}</b></h3>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Tanggal BKU</th>
                <th>Tipe</th>
                <th>Dana</th>
                <th>Keterangan</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

              @foreach($dana as $item)
              <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $item->tanggal->format('d-m-Y') }}</td>
                <td>{{ $item->tanggal_bku->format('d-m-Y') }}</td>
                <td>{{ $item->tipe }}</td>
                <td>{{ number_format($item->dana, 0, ".", ".") }}</td>
                <td>{{ $item->ket }}</td>
                <td align="center">
                  <form action="{{ route('dana.destroy',$item->id) }}" method="POST">
                    <a class="btn btn-success" href="{{ route('dana.edit',$item->id) }}">Ubah</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/dana/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Dana
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ubah Data Dana</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <form action="{{ route('dana.update', $dana->id) }}" class="form-horizontal" method="POST">
            @csrf
            @method('PUT')

            <div class="col-md-12">
              <div class="form-group">
                <label for="tanggal" class="col-sm-2 control-label">Tanggal</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal" class="form-control" value="{{ $dana->tanggal->format('Y-m-d') }}">
                  <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tanggal_bku" class="col-sm-2 control-label">Tanggal BKU</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal_bku" value="{{ $dana->tanggal_bku->format('Y-m-d') }}" class="form-control" placeholder="Tanggal BKU">
                  <small class="text-danger">{{ $errors->first('tanggal_bku') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tipe" class="col-sm-2 control-label">Tipe</label>
                <div class="col-sm-10">
                  <select class="form-control" name="tipe">
                    <option value="{{$dana->tipe}}">{{$dana->tipe}}</option>
                    <option value="Tarik">Tarik</option>
                    <option value="Masuk">Masuk</option>
                  </select>
                  <small class="text-danger">{{ $errors->first('tipe') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tahun" class="col-sm-2 control-label">Dana</label>

                <div class="col-sm-10">
                  <input type="number" name="dana" value="{{ $dana->dana }}" class="form-control" placeholder="Dana">
                  <small class="text-danger">{{ $errors->first('dana') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="ket" class="col-sm-2 control-label">Keterangan</label>

                <div class="col-sm-10">
                  <input type="text" name="ket" value="{{ $dana->ket }}" class="form-control" placeholder="ex : Penarikan Dana 1">
                  <small class="text-danger">{{ $errors->first('ket') }}</small>
                </div>
              </div>
              <a href="{{url('admin/dana')}}" class="btn btn-default">Kembali</a>
              <button type="submit" class="btn btn-primary pull-right">Simpan</button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection