routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index');
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/meta', 'Web\Admin\MetaController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('/admin/tahun', 'Web\Admin\TahunController');
Route::resource('/admin/tahap', 'Web\Admin\TahapController');
Route::resource('/admin/rubah', 'Web\Admin\CookieController');

Route::resource('/admin/dana', 'Web\Admin\DanaController');
Route::resource('/admin/saldo', 'Web\Admin\SaldoController');

Route::resource('/admin/komponen', 'Web\Admin\KomponenController');
Route::get('/admin/subkomponen/index/{id}', 'Web\Admin\SubKomponenController@index');
Route::resource('/admin/subkomponen', 'Web\Admin\SubKomponenController');

Route::get('/admin/nota/index/{id}', 'Web\Admin\NotaController@index');
Route::resource('/admin/nota', 'Web\Admin\NotaController');

Route::resource('/admin/barang', 'Web\Admin\BarangController');
Route::post('importbarang', 'Web\Admin\BarangController@import')->name('importbarang');
Route::get('exportbarang', 'Web\Admin\BarangController@export')->name('exportbarang');

Route::resource('/admin/toko', 'Web\Admin\TokoController');
Route::post('importtoko', 'Web\Admin\TokoController@import')->name('importtoko');
Route::get('exporttoko', 'Web\Admin\TokoController@export')->name('exporttoko');

Route::resource('/admin/notabarang', 'Web\Admin\NotaBarangController');

Route::resource('/admin/cetak/notas', 'Web\Admin\CetakNotaController');
Route::resource('/admin/cetak/apd', 'Web\Admin\CetakAPDController');
Route::resource('/admin/cetak/bku', 'Web\Admin\CetakBKUController');
Route::resource('/admin/cetak/bpp', 'Web\Admin\CetakBPPController');
Route::resource('/admin/cetak/rlpd', 'Web\Admin\CetakRLPDController');
Route::resource('/admin/cetak/bkp', 'Web\Admin\CetakBKPController');

resources/views/admin/cetak/rlpd/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Rekapitulasi Laporan Penggunaan Dana
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-primary" target="_blank" href="{{ route('rlpd.show',1) }}"><i class="fa fa-print"></i> Cetak RLPD</a>
      <br><br>
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Rekapitulasi Laporan Penggunaan Dana - {{Cookie::get('tahap')}} Tahun {{Cookie::get('tahun')}}</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th rowspan="2" width="20px" align="center">No</th>
                <th rowspan="2" align="center" width="100px">Tanggal</th>
                <th colspan="2" align="center">Transaksi</th>
                <th rowspan="2" align="center">Kode Rekening</th>
                <th rowspan="2" align="center" width="300px">Jenis Kegiatan</th>
                <th rowspan="2" align="center">Nama Barang</th>
                <th rowspan="2" align="center">Volume</th>
                <th rowspan="2" align="center">Satuan</th>
                <th colspan="2" align="center">Harga</th>
              </tr>
              <tr>
                <th>Bukti</th>
                <th width="100px">Tanggal</th>
                <th>Satuan</th>
                <th>Jumlah</th>
              </tr>
            </thead>
            <tbody>
              @php
              $totalll = 0;
              @endphp

              @foreach($komponen as $item)
              @foreach($item->sub_komponen as $subkom)
              @foreach($subkom->nota->sortBy('tanggal') as $nota)
              @php
              $total_pajak = 0;
              $jum_harga = 0;
              $total = 0;
              $j=0;
              @endphp

              <!-- NOTA BARANG -->
              @foreach($nota->nota_barang as $hem)
              @php
              $jum_harga = $jum_harga + ($hem->barang->harga*$hem->qty);
              @endphp

              @if($j==0)
              <tr>
                <td align="center">{{$no}}</td>
                <td align="center">
                  @if(empty($item->tanggal_bku))
                  @else
                  Tgl BKU : {{ $item->tanggal_bku->format('d-m-Y') }}
                  @endif
                </td>
                <td align="center">{{$no}}</td>
                <td align="center">{{ $hem->nota->tanggal->format('d-m-Y') }}</td>
                <td align="center">{{$hem->nota->kode_rek}}</td>
                <td>
                  @if($nota->uraian=="")
                  Pelunasan {{$nota->sub_komponen->sub_komponen}}
                  @else
                  Pelunasan {{$nota->uraian}}
                  @endif
                </td>
                <td>{{$hem->barang->barang}}</td>
                <td align="center">{{$hem->qty}}</td>
                <td align="center">{{$hem->barang->satuan}}</td>
                <td align="right">{{$hem->barang->harga}}</td>
                <td align="right">{{ number_format($hem->barang->harga*$hem->qty, 0, ".", ".")}}</td>
              </tr>
              @else
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{$hem->barang->barang}}</td>
                <td align="center">{{$hem->qty}}</td>
                <td align="center">{{$hem->barang->satuan}}</td>
                <td align="right">{{$hem->barang->harga}}</td>
                <td align="right">{{ number_format($hem->barang->harga*$hem->qty, 0, ".", ".")}}</td>
              </tr>
              @endif
              @php $j++ @endphp
              @endforeach

              <tr height="20px">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td align="right">{{ number_format($jum_harga, 0, ".", ".")}}</td>
              </tr>

              @php $no++ @endphp
              <!-- IF KODE PAJAK -->
              @if($nota->kode_pajak=="T")
              <!-- IF KODE PPH 22-->
              @if($nota->kode_pph=="22")
              @if($jum_harga>=1000000)
              @php
              $dasar_pajak = (100/110)*$jum_harga;
              $ppn = (10/100)*$dasar_pajak;
              $r_ppn = round($ppn, -2);
              $pph22 = (1.5/100)*$dasar_pajak;
              $r_pph22 = round($pph22, -2);
              $total_pajak = $r_ppn+$r_pph22;
              $total = $jum_harga+$total_pajak;
              $totalll = $totalll+$total;
              @endphp
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td align="right">Pembayaran PPn</td>
                <td></td>
                <td></td>
                <td align="right">{{ number_format($r_ppn, 0, ".", ".")}}</td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td align="right">Pembayaran PPh.22</td>
                <td></td>
                <td></td>
                <td align="right">{{ number_format($r_pph22, 0, ".", ".")}}</td>
                <td></td>
              </tr>
              @endif
              <!-- END KODE PPH 22 -->
              <!-- IF KODE PPH 21 -->
              @elseif($nota->kode_pph=="21")
              @if($jum_harga>=1000000)
              @php
              $dasar_pajak = (100/110)*$jum_harga;
              $pph21 = (5/100)*$dasar_pajak;
              $r_pph21 = round($pph21, -2);
              $total_pajak = $r_pph21;
              $total = $jum_harga+$total_pajak;
              $totalll = $totalll+$total;
              @endphp
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td align="right">Pembayaran PPh.21</td>
                <td></td>
                <td></td>
                <td align="right">{{ number_format($r_pph21, 0, ".", ".")}}</td>
                <td></td>
              </tr>
              @endif
              @else
              @endif
              <!-- END IF KODE PPH21 -->
              @else
              @php
              $total = $jum_harga;
              $totalll = $totalll+$total;
              @endphp
              @endif
              <!-- END IF KODE PAJAK -->

              <tr style="background-color:#ff9898; font-weight:bold;">
                <td align="center" colspan="10">Jumlah</td>
                <td align="right">{{ number_format($total, 0, ".", ".")}}</td>
              </tr>
              @endforeach
              @endforeach
              @endforeach
              <tr height="20px">
                <td align="center" colspan="10"></td>
                <td></td>
              </tr>
              <tr style="background-color:#71bd68; font-weight:bold;">
                <td align="center" colspan="10">Total Pengeluaran</td>
                <td align="right">{{ number_format($totalll, 0, ".", ".")}}</td>
              </tr>
              <tr style="background-color:#ead35e; font-weight:bold;">
                <td align="center" colspan="10">Total Penerimaan</td>
                <td align="right">{{ number_format($total_dana, 0, ".", ".")}}</td>
              </tr>
              <tr style="background-color:#658dd8; font-weight:bold;">
                <td align="center" colspan="10">Saldo Kas</td>
                <td align="right">{{ number_format($saldo, 0, ".", ".")}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/cetak/rlpd/show.blade.php
<html>

</html>
<!DOCTYPE html>
<html>

<head>
  <title>Rekapitulasi Laporan Penggunaan Dana</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">

  <style>
    @media print {
      @page {
        size: auto !important
      }
    }

    .samping {
      padding: 15px 15px;
    }

    body {
      font-family: 'Source Sans Pro', sans-serif;
    }

    #tabless {
      border: 0px solid black;
    }

    .tablee,
    td,
    th {
      border: 1px solid black;
    }

    .tablee {
      border-collapse: collapse;
      width: 100%;
      margin-bottom: 10px;
    }

    th {
      padding: 5px 5px;
      height: 20px;
      text-align: center;
      font-weight: bold;
    }

    td {
      padding-left: 5px;
      padding-right: 5px;
    }
  </style>
</head>

<body>
  <!-- onload="window.print()" -->
  <div class="samping">
    <center>
      <h4 class="box-title">REKAPITULASI LAPORAN PENGGUNAAN DANA<br>BANTUAN OPERASIONAL SEKOLAH<br>{{Cookie::get('tahap')}} - Tahun {{Cookie::get('tahun')}}</h4>
    </center>
    <br>
    <div class="row">
      <div class="col-2">Nama Sekolah</div>
      <div class="col-3">: {{$nama->profil_value}}</div>
      <div class="col"></div>
      <div class="col-2">Periode</div>
      <div class="col-2">: {{Cookie::get('tahap')}}</div>
    </div>
    <div class="row">
      <div class="col-2">Kabupaten</div>
      <div class="col-3">: {{$kab->profil_value}}</div>
      <div class="col"></div>
      <div class="col-2">Bulan</div>
      <div class="col-2">: {{ $bulan->meta_value }}</div>
    </div>
    <div class="row">
      <div class="col-2">Provinsi</div>
      <div class="col-3">: {{$prov->profil_value}}</div>
      <div class="col"></div>
      <div class="col-2">Tahun</div>
      <div class="col-2">: {{Cookie::get('tahun')}}</div>
    </div>
    <div class="row">
      <div class="col-2">Jenis Kegiatan</div>
      <div class="col-3">: {{$jenis->meta_value}}</div>
      <div class="col"></div>
    </div>
    <br>

    <table class="tablee">
      <thead>
        <tr>
          <th rowspan="2" width="20px" align="center">No</th>
          <th rowspan="2" align="center" width="100px">Tanggal</th>
          <th colspan="2" align="center">Transaksi</th>
          <th rowspan="2" align="center">Kode Rekening</th>
          <th rowspan="2" align="center" width="300px">Jenis Kegiatan</th>
          <th rowspan="2" align="center">Nama Barang</th>
          <th rowspan="2" align="center">Volume</th>
          <th rowspan="2" align="center">Satuan</th>
          <th colspan="2" align="center">Harga</th>
        </tr>
        <tr>
          <th>Bukti</th>
          <th width="100px">Tanggal</th>
          <th>Satuan</th>
          <th>Jumlah</th>
        </tr>
      </thead>
      <tbody>
        @php
        $totalll = 0;
        @endphp

        @foreach($komponen as $item)
        @foreach($item->sub_komponen as $subkom)
        @foreach($subkom->nota->sortBy('tanggal') as $nota)
        @php
        $total_pajak = 0;
        $jum_harga = 0;
        $total = 0;
        $j=0;
        @endphp

        <!-- NOTA BARANG -->
        @foreach($nota->nota_barang as $hem)
        @php
        $jum_harga = $jum_harga + ($hem->barang->harga*$hem->qty);
        @endphp

        @if($j==0)
        <tr>
          <td align="center">{{$no}}</td>
          <td align="center">
            @if(empty($item->tanggal_bku))
            @else
            Tgl BKU : {{ $item->tanggal_bku->format('d-m-Y') }}
            @endif
          </td>
          <td align="center">{{$no}}</td>
          <td align="center">{{ $hem->nota->tanggal->format('d-m-Y') }}</td>
          <td align="center">{{$hem->nota->kode_rek}}</td>
          <td>
            @if($nota->uraian=="")
            Pelunasan {{$nota->sub_komponen->sub_komponen}}
            @else
            Pelunasan {{$nota->uraian}}
            @endif
          </td>
          <td>{{$hem->barang->barang}}</td>
          <td align="center">{{$hem->qty}}</td>
          <td align="center">{{$hem->barang->satuan}}</td>
          <td align="right">{{$hem->barang->harga}}</td>
          <td align="right">{{ number_format($hem->barang->harga*$hem->qty, 0, ".", ".")}}</td>
        </tr>
        @else
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>{{$hem->barang->barang}}</td>
          <td align="center">{{$hem->qty}}</td>
          <td align="center">{{$hem->barang->satuan}}</td>
          <td align="right">{{$hem->barang->harga}}</td>
          <td align="right">{{ number_format($hem->barang->harga*$hem->qty, 0, ".", ".")}}</td>
        </tr>
        @endif
        @php $j++ @endphp
        @endforeach

        <tr height="20px">
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td align="right">{{ number_format($jum_harga, 0, ".", ".")}}</td>
        </tr>

        @php $no++ @endphp
        <!-- IF KODE PAJAK -->
        @if($nota->kode_pajak=="T")
        <!-- IF KODE PPH 22-->
        @if($nota->kode_pph=="22")
        @if($jum_harga>=1000000)
        @php
        $dasar_pajak = (100/110)*$jum_harga;
        $ppn = (10/100)*$dasar_pajak;
        $r_ppn = round($ppn, -2);
        $pph22 = (1.5/100)*$dasar_pajak;
        $r_pph22 = round($pph22, -2);
        $total_pajak = $r_ppn+$r_pph22;
        $total = $jum_harga+$total_pajak;
        $totalll = $totalll+$total;
        @endphp
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td align="right">Pembayaran PPn</td>
          <td></td>
          <td></td>
          <td align="right">{{ number_format($r_ppn, 0, ".", ".")}}</td>
          <td align="right">{{ number_format($r_ppn, 0, ".", ".")}}</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td align="right">Pembayaran PPh.22</td>
          <td></td>
          <td></td>
          <td align="right">{{ number_format($r_pph22, 0, ".", ".")}}</td>
          <td align="right">{{ number_format($r_pph22, 0, ".", ".")}}</td>
        </tr>
        @endif
        <!-- END KODE PPH 22 -->
        <!-- IF KODE PPH 21 -->
        @elseif($nota->kode_pph=="21")
        @if($jum_harga>=1000000)
        @php
        $dasar_pajak = (100/110)*$jum_harga;
        $pph21 = (5/100)*$dasar_pajak;
        $r_pph21 = round($pph21, -2);
        $total_pajak = $r_pph21;
        $total = $jum_harga+$total_pajak;
        $totalll = $totalll+$total;
        @endphp
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td align="right">Pembayaran PPh.21</td>
          <td></td>
          <td></td>
          <td align="right">{{ number_format($r_pph21, 0, ".", ".")}}</td>
          <td align="right">{{ number_format($r_pph21, 0, ".", ".")}}</td>
        </tr>
        @endif
        @else
        @endif
        <!-- END IF KODE PPH21 -->
        @else

        @php
        $total = $jum_harga;
        $totalll = $totalll+$total;
        @endphp
        @endif
        <!-- END IF KODE PAJAK -->

        <tr style="background-color:#ff9898; font-weight:bold;">
          <td align="center" colspan="10">Jumlah</td>
          <td align="right">{{ number_format($total, 0, ".", ".")}}</td>
        </tr>
        @endforeach
        @endforeach
        @endforeach
        <tr height="20px">
          <td align="center" colspan="10"></td>
          <td></td>
        </tr>
        <tr style="background-color:#71bd68; font-weight:bold;">
          <td align="center" colspan="10">Total Pengeluaran</td>
          <td align="right">{{ number_format($totalll, 0, ".", ".")}}</td>
        </tr>
        <tr style="background-color:#ead35e; font-weight:bold;">
          <td align="center" colspan="10">Total Penerimaan</td>
          <td align="right">{{ number_format($total_dana, 0, ".", ".")}}</td>
        </tr>
        <tr style="background-color:#658dd8; font-weight:bold;">
          <td align="center" colspan="10">Saldo Kas</td>
          <td align="right">{{ number_format($saldo, 0, ".", ".")}}</td>
        </tr>
        <tr height="20px">
          <td colspan="10"></td>
          <td></td>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <div class="col"></div>
      <div class="col-3" align="center">
        @foreach($profil as $prof)
        @if($prof->profil_key==="Desa")
        {{$prof->profil_value}},
        @endif
        @endforeach
        ......................... {{Cookie::get('tahun')}}
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-3" align="center">Mengetahui / Menyutujui<br>Komite Sekolah</div>
      <div class="col" align="center">Bendahara</div>
      <div class="col-3" align="center">Kepala SMK Pelita</div>
    </div>
    <br><br><br>
    <div class="row">
      <div class="col-3" align="center">
        @foreach($profil as $prof)
        @if($prof->profil_key==="Komite Sekolah")
        {{$prof->profil_value}}
        @endif
        @endforeach
      </div>
      <div class="col" align="center">
        @foreach($profil as $prof)
        @if($prof->profil_key==="Bendahara Sekolah")
        <br>
        {{$prof->profil_value}}
        @endif
        @endforeach
      </div>
      <div class="col-3" align="center">
        @foreach($profil as $prof)
        @if($prof->profil_key==="Kepala Sekolah")
        <br>
        {{$prof->profil_value}}
        @endif
        @endforeach
      </div>
    </div>
  </div>

</body>

</html>