routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index');
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/profil', 'Web\Admin\ProfilController');
Route::resource('/admin/meta', 'Web\Admin\MetaController');
Route::resource('/admin/history', 'Web\Admin\HistoryController');
Route::resource('/admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('/admin/tahun', 'Web\Admin\TahunController');
Route::resource('/admin/tahap', 'Web\Admin\TahapController');
Route::resource('/admin/rubah', 'Web\Admin\CookieController');

Route::resource('/admin/dana', 'Web\Admin\DanaController');
Route::resource('/admin/saldo', 'Web\Admin\SaldoController');

Route::resource('/admin/komponen', 'Web\Admin\KomponenController');
Route::get('/admin/subkomponen/index/{id}', 'Web\Admin\SubKomponenController@index');
Route::resource('/admin/subkomponen', 'Web\Admin\SubKomponenController');

Route::get('/admin/nota/index/{id}', 'Web\Admin\NotaController@index');
Route::resource('/admin/nota', 'Web\Admin\NotaController');

Route::resource('/admin/barang', 'Web\Admin\BarangController');
Route::post('importbarang', 'Web\Admin\BarangController@import')->name('importbarang');
Route::get('exportbarang', 'Web\Admin\BarangController@export')->name('exportbarang');

Route::resource('/admin/toko', 'Web\Admin\TokoController');
Route::post('importtoko', 'Web\Admin\TokoController@import')->name('importtoko');
Route::get('exporttoko', 'Web\Admin\TokoController@export')->name('exporttoko');

Route::resource('/admin/notabarang', 'Web\Admin\NotaBarangController');

Route::resource('/admin/cetak/notas', 'Web\Admin\CetakNotaController');
Route::resource('/admin/cetak/apd', 'Web\Admin\CetakAPDController');
Route::resource('/admin/cetak/bku', 'Web\Admin\CetakBKUController');
Route::resource('/admin/cetak/bpp', 'Web\Admin\CetakBPPController');
Route::resource('/admin/cetak/rlpd', 'Web\Admin\CetakRLPDController');
Route::resource('/admin/cetak/bkp', 'Web\Admin\CetakBKPController');

app/Saldo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Saldo extends Model
{
    protected $fillable = [
        'tahap_id','tanggal','saldo','ket',
    ];
    
    protected $dates = ['tanggal'];

    public function tahap()
    {
        return $this->belongsTo('App\Tahap', 'tahap_id');
    }
}

app/Http/Controllers/Web/Admin/SaldoController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\SaldoRequest;
use App\Saldo;
use App\Tahap;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;

class SaldoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $no =1;
        $tahap = Cookie::get('tahap');
        $tahun_id = Cookie::get('id_tahun');
        $tahap_id = Tahap::where('tahun_id',$tahun_id)->where('tahap',$tahap)->get()->first();

        $saldo = Saldo::where('tahap_id', $tahap_id->id)->orderBy('tanggal', 'ASC')->get()->all();
        $total_saldo = Saldo::where('tahap_id', $tahap_id)->sum('saldo');
        return view('admin.saldo.beranda', compact('saldo','no','total_saldo'));
    }

    public function create()
    {
        //
    }

    public function store(SaldoRequest $request)
    {
        $tahap = Cookie::get('tahap');
        $tahun_id = Cookie::get('id_tahun');
        $tahap_id = Tahap::where('tahun_id',$tahun_id)->where('tahap',$tahap)->get()->first();

        $data = $request->all();
        $data['tahap_id'] = $tahap_id->id;

        Saldo::create($data);
        
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Saldo " . $request->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Saldo "' . $request->ket . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('saldo.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit(Saldo $saldo)
    {
        return view('admin.saldo.edit',compact('saldo'));
    }

    public function update(SaldoRequest $request, Saldo $saldo)
    {
        $saldo->update($request->all());
  
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Saldo " . $request->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Saldo "' . $request->ket . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('saldo.index')->with($notification);
    }

    public function destroy(Saldo $saldo)
    {
        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Saldo " . $saldo->ket;
        History::create($histori);

        $notification = array(
            'message' => 'Data Saldo "' . $saldo->ket . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $saldo->delete();

        return redirect()->route('saldo.index')->with($notification);
    }
}

resources/views/admin/saldo/beranda.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Saldo
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Saldo</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <form action="{{ route('saldo.store') }}" class="form-horizontal" method="POST">
            @csrf

            <div class="col-md-6">
              <div class="form-group">
                <label for="tanggal" class="col-sm-2 control-label">Tanggal</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal" class="form-control" placeholder="Tanggal">
                  <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="saldo" class="col-sm-2 control-label">Saldo</label>

                <div class="col-sm-10">
                  <input type="number" name="saldo" class="form-control" placeholder="Saldo">
                  <small class="text-danger">{{ $errors->first('saldo') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="ket" class="col-sm-2 control-label">Keterangan</label>

                <div class="col-sm-10">
                  <input type="text" name="ket" class="form-control" placeholder="ex : Saldo Bulan Januari">
                  <small class="text-danger">{{ $errors->first('ket') }}</small>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Simpan</button>
            </div>

          </form>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <h3><b>Total Saldo : {{ number_format($total_saldo, 0, ".", ".") }}</b></h3>
        </div>
        <hr>
        <div class="box-body" style="overflow-x:auto;">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Saldo</th>
                <th>Keterangan</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

              @foreach($saldo as $item)
              <tr>
                <td>{{ $no++ }}</td>
                <td>{{ $item->tanggal->format('d-m-Y') }}</td>
                <td>{{ number_format($item->saldo, 0, ".", ".") }}</td>
                <td>{{ $item->ket }}</td>
                <td align="center">
                  <form action="{{ route('saldo.destroy',$item->id) }}" method="POST">
                    <a class="btn btn-success" href="{{ route('saldo.edit',$item->id) }}">Ubah</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/saldo/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

  <section class="content-header">
    <h1>
      Saldo
    </h1>
  </section><br><br>

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ubah Data Saldo</h3>
        </div>

        <div class="box-body" style="overflow-x:auto;">
          <form action="{{ route('saldo.update', $saldo->id) }}" class="form-horizontal" method="POST">
            @csrf
            @method('PUT')

            <div class="col-md-12">
              <div class="form-group">
                <label for="tanggal" class="col-sm-2 control-label">Tanggal</label>

                <div class="col-sm-10">
                  <input type="date" name="tanggal" class="form-control" value="{{ $saldo->tanggal->format('Y-m-d') }}">
                  <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="tahun" class="col-sm-2 control-label">Saldo</label>

                <div class="col-sm-10">
                  <input type="number" name="saldo" value="{{ $saldo->saldo }}" class="form-control" placeholder="Saldo">
                  <small class="text-danger">{{ $errors->first('saldo') }}</small>
                </div>
              </div>
              <div class="form-group">
                <label for="ket" class="col-sm-2 control-label">Keterangan</label>

                <div class="col-sm-10">
                  <input type="text" name="ket" value="{{ $saldo->ket }}" class="form-control" placeholder="ex : Penarikan saldo 1">
                  <small class="text-danger">{{ $errors->first('ket') }}</small>
                </div>
              </div>
              <a href="{{url('admin/saldo')}}" class="btn btn-default">Kembali</a>
              <button type="submit" class="btn btn-primary pull-right">Simpan</button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection